apiVersion: v1
description: Iguazio NetOps demo
name: netops
version: 0.0.1
appVersion: 0.0.1
icon: https://github.com/nuclio/nuclio/raw/master/docs/assets/images/logo.png
home: https://iguazio.com
maintainers:
  - name: Eran Duchan
    email: erand@iguazio.com
